## Imports 

In [1]:
from SETUP import *
from REDUCE_FEATURES import *
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
%matplotlib inline

from sklearn.model_selection import train_test_split

In [2]:
data_file = '/Users/Winnifred/Desktop/Capstone/ICPSR_20240_RAWDATA/DS0001/20240-0001-Data.tsv'
filenames = '/Users/Winnifred/Desktop/Capstone/diagnosis_capstone/data/feature_group_file_names.txt'
csv_root_path = '/Users/Winnifred/Desktop/Capstone/diagnosis_capstone/data/feature_name_data/'

In [3]:
suicidality_features = ['V01995', 'V01997', 'V01999', 'V02044', 'V02003', 'V02004', 'V02009', 'V02023', 'V02025', 'V02027', 'V02029', 'V02031', 'V02032', 'V02035', 'V02036', 'V02041']

In [4]:
set_inst = Setup(csv_root_path, filenames)
full_dict = set_inst.execute_setup()
reduce_inst = Reduce_Features(data_file, full_dict)
dirty_df = reduce_inst.execute_reduce()

In [5]:
df = dirty_df.drop(dirty_df[dirty_df['V01993'] == ' '].index)

In [6]:
## Turn strings to ints 
mask = {str(num): num for num in range(200000)}

In [7]:
mask[' '] = 0

In [8]:
mask['-9'] = -9

In [9]:
mask['-8'] = -8

In [10]:
mask[None] = 0

In [11]:
for idx, feature in enumerate(list(df)): 
    df[feature] = df[feature].map(mask)
    if idx % 250 == 0: 
        print('completed feature {} of 2110'.format(idx))

completed feature 0 of 2110
completed feature 250 of 2110
completed feature 500 of 2110
completed feature 750 of 2110
completed feature 1000 of 2110


In [12]:
df.drop(suicidality_features, axis=1, inplace=True)

In [13]:
df.head()

V01638  V01639  V01643  V01644  V01646  V01647  V01648  V01649  V01650  \
0       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
5       0       0       0       0       0       0       0       0       0   
6       0       0       0       0       0       0       0       0       0   

   V01651   ...    V08495  V08549  V07725  V07894  V08501  V08500  V08553  \
0       0   ...         5       5       5       5       5       5       5   
2       0   ...         5       5       1       1       5       5       5   
3       0   ...         5       5       5       5       5       5       5   
5       0   ...         5       5       5       5       5       5       5   
6       0   ...         5       5       5       5       5       5       5   

   V07750  V07748  V07899  
0       5       5       5  
2       5       5       5  
3       5       5       5  
5       5       5       5  
6       5       5       5  

[5 rows x 1201 columns]

In [14]:
df = df.dropna(axis=1)

In [15]:
df['V01993'].describe()

count    15890.000000
mean         4.456765
std          1.429194
min         -9.000000
25%          5.000000
50%          5.000000
75%          5.000000
max          5.000000
Name: V01993, dtype: float64

In [16]:
X_df = df.loc[:, df.columns != 'V01993']
y_df = df['V01993'].map({5:0, 1:1, -9:0, -8:0})

In [17]:
X = X_df.as_matrix()
y = y_df.as_matrix()

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [19]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(10646, 1192) (10646,)
(5244, 1192) (5244,)


In [20]:
def print_scores(y_test, predictions):
    print('Accuracy:', accuracy_score(y_test, predictions))
    print('Precision:', precision_score(y_test, predictions))
    print('Recall:', recall_score(y_test, predictions))
    return None

# Step 3  - MODELING


In [23]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import confusion_matrix, roc_curve
from sklearn import linear_model

In [31]:
from sklearn.preprocessing import StandardScaler

## Logistic Regression

In [32]:
logreg = linear_model.LogisticRegression()

In [33]:
ss = StandardScaler()

In [34]:
ss.fit(X_train)
s_X_train = ss.transform(X_train)
ss.fit(X_test)
s_X_test = ss.transform(X_test)

/Users/Winnifred/anaconda2/envs/py3/lib/python3.6/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)


In [35]:
X_train

array([[0, 0, 0, ..., 5, 5, 1],
       [0, 0, 0, ..., 5, 5, 5],
       [0, 0, 0, ..., 5, 5, 5],
       ..., 
       [0, 0, 0, ..., 5, 5, 5],
       [0, 0, 0, ..., 5, 5, 5],
       [0, 0, 0, ..., 5, 5, 5]])

In [36]:
s_X_train

array([[-0.11051196, -0.11633148, -0.02385725, ...,  0.17115833,
         0.24803546, -3.12132731],
       [-0.11051196, -0.11633148, -0.02385725, ...,  0.17115833,
         0.24803546,  0.32037653],
       [-0.11051196, -0.11633148, -0.02385725, ...,  0.17115833,
         0.24803546,  0.32037653],
       ..., 
       [-0.11051196, -0.11633148, -0.02385725, ...,  0.17115833,
         0.24803546,  0.32037653],
       [-0.11051196, -0.11633148, -0.02385725, ...,  0.17115833,
         0.24803546,  0.32037653],
       [-0.11051196, -0.11633148, -0.02385725, ...,  0.17115833,
         0.24803546,  0.32037653]])

In [37]:
X_test

array([[0, 0, 0, ..., 5, 5, 5],
       [0, 0, 0, ..., 5, 5, 5],
       [0, 0, 0, ..., 5, 5, 5],
       ..., 
       [0, 0, 0, ..., 5, 5, 5],
       [0, 0, 0, ..., 5, 5, 5],
       [0, 0, 0, ..., 5, 5, 5]])

In [39]:
s_X_test

array([[-0.1163206 , -0.0947035 , -0.05982626, ...,  0.16378622,
         0.25022786,  0.3314231 ],
       [-0.1163206 , -0.0947035 , -0.05982626, ...,  0.16378622,
         0.25022786,  0.3314231 ],
       [-0.1163206 , -0.0947035 , -0.05982626, ...,  0.16378622,
         0.25022786,  0.3314231 ],
       ..., 
       [-0.1163206 , -0.0947035 , -0.05982626, ...,  0.16378622,
         0.25022786,  0.3314231 ],
       [-0.1163206 , -0.0947035 , -0.05982626, ...,  0.16378622,
         0.25022786,  0.3314231 ],
       [-0.1163206 , -0.0947035 , -0.05982626, ...,  0.16378622,
         0.25022786,  0.3314231 ]])

In [40]:
lr_model = logreg.fit(s_X_train, y_train)

In [41]:
lr_y_pred = logreg.predict(s_X_test)

In [43]:
print('Score:', lr_model.score(s_X_test, y_test))

Score: 0.880434782609


In [45]:
print_scores(y_test, lr_y_pred)

Accuracy: 0.880434782609
Precision: 0.526703499079
Recall: 0.435975609756


## Random Forest

In [47]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn import svm, metrics
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import learning_curve

In [48]:
rfc = RandomForestClassifier(bootstrap= True,
 class_weight= None,
 criterion= 'gini',
 max_depth= 20,
 max_features= 'auto',
 max_leaf_nodes= None,
 min_impurity_split= 1e-07,
 min_samples_leaf= 20,
 min_samples_split= 40,
 min_weight_fraction_leaf= 0.0,
 n_estimators= 150,
 n_jobs= 1,
 oob_score= True,
 random_state= 0,
 verbose= 0,
 warm_start= False)

In [49]:
rf_model = rfc.fit(X_train, y_train)

In [50]:
print(rfc.feature_importances_)

[  5.37897028e-05   1.75062066e-04   0.00000000e+00 ...,   1.73964380e-04
   2.34750403e-04   2.45589985e-04]


In [52]:
rf_y_pred = rf_model.predict(X_test)

In [53]:
rf_model.score(X,y)

0.9078665827564506

In [55]:
print_scores(y_test, rf_y_pred)

Accuracy: 0.907513348589
Precision: 0.776699029126
Recall: 0.365853658537


In [ ]:
pd.DataFrame(
    confusion_matrix(y_test, lr_y_pred),
    columns=['Predicted: No Ideation', 'Predicted: Ideation'],
    index=['Actual: No Ideation', 'Actual: Ideation']
)

In [ ]:
pd.DataFrame(
    confusion_matrix(y_test, rfc_y_pred),
    columns=['Predicted: No Ideation', 'Predicted: Ideation'],
    index=['Actual: No Ideation', 'Actual: Ideation']
)

In [ ]:
train_pred = lr_model.predict(X_train)
print_scores(y_train, train_pred)

In [ ]:
train_pred = rfc.predict(X_train)
print_scores(y_train, train_pred)

# .........................................................................................................................................

## ROC Curve

In [ ]:
lr_model = logreg.fit(X_train, y_train)
lr_preds = lr_model.predict_proba(X_test)[:,1]
lr_fpr, lr_tpr, _ = roc_curve(y_test, lr_preds)
lr_df = pd.DataFrame(dict(fpr=lr_fpr, tpr=lr_tpr))
lr_df.plot()

In [ ]:
rf_model = rfc.fit(X_train, y_train)
rf_preds = rf_model.predict_proba(X_test)[:,1]
rf_fpr, rf_tpr, _ = roc_curve(y_test, rf_y_pred)
rf_df = pd.DataFrame(dict(fpr=rf_fpr, tpr=rf_tpr))
rf_roc_auc = metrics.auc(rf_fpr, rf_tpr)

rf_df.plot()

In [ ]:
lr_fig = plt.figure(1, figsize=(6,6))

plt.subplot()
lr_many_features = plt.plot(lr_df.fpr, lr_df.tpr, label='LR Many Features', alpha=0.7)

plt.subplot()
lr_few_features = plt.plot(LR_SM_df.fpr, LR_SM_df.tpr, label='LR Few Features', alpha=0.7)

plt.plot([0,1],[0,1], color='#ADD8E6')

# plt.subplot()
# rf_many_features = plt.plot(rf_df.fpr, rf_df.tpr, label='RF Many Features', alpha=0.7)

# plt.subplot()
# rf_few_features = plt.plot(RF_SM_df.fpr, RF_SM_df.tpr, label='RF Few Features', alpha=0.7)

plt.xlabel('False Positive Rate',{'fontsize':15},color='#0b5394')
plt.ylabel('True Positive Rate',{'fontsize':15},color='#0b5394')

plt.title("Logistic Regression ROC",{'fontsize':20},color='#0b5394')

# plt.legend(handles=many_features)

plt.show()

In [ ]:
lr_fig.savefig('roc_draft.png')

## Adding Subplot from Other File

DATAFRAME FOR RANDOM FOREST WITH FEW FEATURES 

In [ ]:
path = '/Users/Winnifred/Desktop/Capstone/diagnosis_capstone/src/basic_roc_df.csv'

In [ ]:
RF_SM_df = pd.read_csv(path)

DATAFRAME FOR RANDOM FOREST WITH FEW FEATURES 

In [ ]:
path = '/Users/Winnifred/Desktop/Capstone/diagnosis_capstone/src/lr_basic_roc_df.csv'

In [ ]:
LR_SM_df = pd.read_csv(path)